# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: DockerInstaller@0
  displayName: Insatll Docker
  inputs:
    dockerVersion: '17.09.0-ce'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'ToDocker'
#     command: 'login'


# - task: Docker@2
#   displayName: Build and Push an image
#   inputs:
#     containerRegistry: 'ToDocker'
#     repository: 'dockerimage'
- task: Docker@2
  inputs:
    containerRegistry: 'ToDocker'
    repository: 'https://index.docker.io/v1/'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '$(Build.ArtifactStagingDirectory)'
- task: Docker@2
  inputs:
    containerRegistry: 'ToDocker'
    repository: 'https://index.docker.io/v1/'
    command: 'push'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile
# - task: Docker@2
#   inputs:
#     command: 'push'